const fs=require('fs');
let c=fs.readFileSync('src/pages/Settings.tsx','utf8');
c=c.replace(/className=\"flex h-8 w-8 items-center\s+justify-center rounded-xl/g, 'className=\"flex h-7 w-7 items-center justify-center rounded-[8px]');
c=c.replace(/className=\{flex h-8 w-8 items-center\s+justify-center rounded-xl/g, 'className=\{flex h-7 w-7 items-center justify-center rounded-[8px]');
c=c.replace(/className=\{flex h-8 w-8 shrink-0/, 'className=\{flex h-7 w-7 shrink-0');
c=c.replace(/className=\"flex h-8 w-8 shrink-0/g, 'className=\"flex h-7 w-7 shrink-0');
c=c.replace(/<BriefcaseBusiness className=\"h-5 w-5\"/g, '<BriefcaseBusiness className=\"h-4 w-4\"');
c=c.replace(/<User className=\"h-5 w-5\"/g, '<User className=\"h-4 w-4\"');
c=c.replace(/<CheckCircle2 className=\"h-5 w-5\"/g, '<CheckCircle2 className=\"h-4 w-4\"');
c=c.replace(/<AlertCircle className=\"h-5 w-5\"/g, '<AlertCircle className=\"h-4 w-4\"');
c=c.replace(/<CreditCard className=\"h-6 w-6 /g, '<CreditCard className=\"h-4 w-4 ');
fs.writeFileSync('src/pages/Settings.tsx',c);
